---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ecodados

<!-- badges: start -->
<!-- badges: end -->

## Instalação

Você pode instalar o pacote `ecodados` através do comando:

```{r, eval=FALSE}
devtools::install_github("paternogbc/ecodados")
```


## Conjuntos de dados disponíveis

N | Nome                | Análise        | Referência     | Link     |
--| ------------------- | -------------- | ---------------| -------- |
1 | rarefa_morcegos     | Rarefação      | XXX            | [link](data-raw/rarefa_morcegos.csv) |
2 | rarefa_repeteis     | Rarefação      | XXX            | [link]() |
3 | rarefa_anuros       | Rarefação      | XXX            | [link]() |
4 | poca_anuros         | Rarefação      | XXX            | [link]() |


## Como usar?

Para carregar todos os conjuntos de dados:

```{r example}
library(ecodados)
head(rarefacao_morcegos)
```

